---
# @var users_general:description: List of global users
# @var users_general:example: >
# users_general:
#   - name: thomas
#     primary_group: staff
#     comment: Thomas Mustermann
#     ansible.builtin.shell: /bin/bash
#     castles:
#       - tboerger/homeshick-base
#       - name: tboerger/homeshick-osx
#         force: true
#     groups:
#       - admin
#     sshkeys:
#       - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINaQYR0/Oj6k1H03kshz2J7rlGCaDSuaGPhhOs9FcZfn tboerger@host1
#       - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC7oOi3qaDtfQVFhPKyd0Wk0C/y+QM71vtln8Rl44NlB tboerger@host2
#       - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFcPTmdo+7eK+8n2yE7Kx1vyQ4yJwHBngvQOt1MPhKhR tboerger@host3
#   - name: buser
#     primary_group: staff
#     ansible.builtin.shell: /bin/bash
#     bashit: true
#     groups:
#       - admin
#   - name: zuser
#     primary_group: staff
#     ansible.builtin.shell: /bin/zsh
#     ohmyzsh: true
#     groups:
#       - admin
#   - name: user-to-delete
#     remove: true
#     state: absent
# @end
users_general: []

# @var users_extra:description: List of extra users
# @var users_extra:example: >
# users_extra:
#   - name: thomas
#     primary_group: staff
#     comment: Thomas Mustermann
#     ansible.builtin.shell: /bin/bash
#     castles:
#       - tboerger/homeshick-base
#       - name: tboerger/homeshick-osx
#         force: true
#     groups:
#       - admin
#     sshkeys:
#       - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINaQYR0/Oj6k1H03kshz2J7rlGCaDSuaGPhhOs9FcZfn tboerger@host1
#       - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC7oOi3qaDtfQVFhPKyd0Wk0C/y+QM71vtln8Rl44NlB tboerger@host2
#       - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFcPTmdo+7eK+8n2yE7Kx1vyQ4yJwHBngvQOt1MPhKhR tboerger@host3
#   - name: buser
#     primary_group: staff
#     ansible.builtin.shell: /bin/bash
#     bashit: true
#     groups:
#       - admin
#   - name: zuser
#     primary_group: staff
#     ansible.builtin.shell: /bin/zsh
#     ohmyzsh: true
#     groups:
#       - admin
#   - name: user-to-delete
#     remove: true
#     state: absent
# @end
users_extra: []

# @var users_packages_general:description: List of general packages to install
users_packages_general:
  - acl
  - bash
  - git

# @var users_packages_zsh:description: List of packages for zsh to install
users_packages_zsh:
  - zsh

# @var users_packages_zfs:description: List of packages for zfs to install
users_packages_zfs:
  - zsys

# @var users_castles_force:description: Force to update homeshick castels
users_castles_force: false

# @var users_ohmyzsh_version:description: Version of bash-it to install
users_ohmyzsh_version: latest

# @var users_bashit_version:description: Version of bash-it to install
users_bashit_version: latest

# @var users_homeshick_version:description: Version of homeshick to install
users_homeshick_version: latest

# @var users_override_zshenv:description: Override zshenv provided by system
users_override_zshenv: true

# @var users_enable_profile_load:description: Enable loading of profile.d within zshenv
users_enable_profile_load: true

# @var users_zfs_home:description: Enable home on ZFS by zsysctl command
users_zfs_home: false

...
